# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"FunctionNames": "product-sdk.ipynb",
         "ProductSdk": "product-sdk.ipynb"}

modules = ["inventory.py"]

doc_url = "https://nic.github.io/villaInventorySdk/"

git_url = "https://github.com/nic/villaInventorySdk/tree/master/"

def custom_doc_links(name): return None
