# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"S3": "00_core.ipynb",
         "InventorySdk": "00_core.ipynb"}

modules = ["inventory.py"]

doc_url = "https://nic.github.io/nbdev_template/"

git_url = "https://github.com/nic/nbdev_template/tree/master/"

def custom_doc_links(name): return None
