# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Response": "Schema.ipynb",
         "Event": "Schema.ipynb",
         "Product": "Schema.ipynb",
         "Products": "Schema.ipynb",
         "FunctionNames": "product-sdk.ipynb",
         "ProductSdk": "product-sdk.ipynb"}

modules = ["schema.py",
           "products.py"]

doc_url = "https://nic.github.io/villaProductSdk/"

git_url = "https://github.com/nic/villaProductSdk/tree/master/"

def custom_doc_links(name): return None
